services:
  - type: web
    name: django-backend
    runtime: python
    buildCommand: |
      # Phase 1: Python setup
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      
      # Phase 2: Build React (Vite)
      cd frontend && npm install && npm run build && cd ..
      
      # Phase 3: Prepare Django static files
      mkdir -p backend/static backend/templates
      cp -r frontend/dist/* backend/static/
      cp frontend/dist/index.html backend/templates/
      
      # Phase 4: Database and static files
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: AITS
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://groupaaits-isnj.onrender.com"